### ISSUE TITLE
Whitespace causing grep to fail

### ISSUE THREAD

**Issue by jakebresnehan** [pdclark/deploy-plugin-to-wordpress-dot-org#1]
Hey @brainstormmedia,

Nice work on the script. Super handy! 

I was thinking of sending over a pull-request but I thought it is probably better to discuss it first.

I had a few issues with the second grep. (https://github.com/brainstormmedia/deploy-plugin-to-wordpress-dot-org/blob/master/deploy.sh#L32) mainly due to my code indenting by two spaces.

`
/\*  
  Plugin Name: Campaign Monitor Dashboard
  Version: 1.0.6
  ...
*/

Might be an idea to add a little section in the `readme.md` about how whitespace can cause the grep to fail.

All worked a treat once removed.

Thanks again!

**Comment by pdclark** [comment]
Thanks for the note! I'm glad to hear it's been helpful for you — it saves us a lot of frustration!

Looks like changing the `grep` to `"^\s*Version` would resolve it. I'll happily approve a pull request.

**Comment by jakebresnehan** [comment]
Cheers @pdclark!

I'll do some more testing on my end and if all good flick it over.
