### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by dmgawel** [pdclark/deploy-plugin-to-wordpress-dot-org#5]
It would be great if assets dir content from plugins base dir would be added to svn /assets and excluded from /trunk.

**Comment by pdclark** [comment]
I'd consider a Pull Request that included this as an option. I don't think it'd be appropriate for an "always-on" feature, though, since many plugin developers use an `assets` directory in the root of the plugin for CSS/JS assets, rather than a reference to the SVN assets directory for screenshots.
